# Generated by Django 4.1.5 on 2024-02-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='images',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='user_api.image'),
        ),
    ]
