# Generated by Django 4.1.5 on 2024-02-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
