# Generated by Django 4.1.5 on 2024-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_id',
            new_name='author',
        ),
    ]
