# Generated by Django 4.1.5 on 2024-03-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
