# Generated by Django 4.1.5 on 2024-02-17 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField()),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.blogpost')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='posts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(related_name='blog_posts', to='user_api.image'),
        ),
    ]
