# Generated by Django 4.1.5 on 2024-02-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_rating_image_blogpost_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.category'),
        ),
    ]
