# Generated by Django 4.1.5 on 2024-03-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_comment_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rate_id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reader',
            new_name='user_id',
        ),
    ]
